name: Hello World
on: workflow_dispatch
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Step
        run: |
          echo "Welcome to Git Hub Actions - Line 1"
          echo "Welcome to GHA - Line 2"
