name: Delete Old Runs
on:
  schedule:
    - cron: '0 0 1 * *' # Runs at midnight on the 1st of every month
  workflow_dispatch:   # Allows you to run it manually

jobs:
  delete-runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0 # Change this to 30 if you want to keep a month's history
          keep_minimum_runs: 0
