name: Inputs Demo
on: 
  workflow_dispatch: 
    inputs: 
      environment:
        description: Choose the environment to deploy
        type: choice
        required: true
        default: dev
        options:
          - dev
          - test
          - QA
          - prod
      artifact_tag:
        description: Choose the Git Tag
        required: true
jobs:
    inputs-demo:
      runs-on: ubuntu-latest
      steps:
        - name: Deploy the API
          run : echo "Deploying the ${{inputs.artifact_tag }} App to ${{ inputs.environment }}"
